/**
 * Siigo.Alliances API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MediaModelStructure from './MediaModelStructure';
import OtherAlliancesModel from './OtherAlliancesModel';
import RequestContactDataFieldsModelStructure from './RequestContactDataFieldsModelStructure';
import TermsModel from './TermsModel';
import UserDataViewModel from './UserDataViewModel';

/**
 * The AllianceDetailsViewModel model module.
 * @module model/AllianceDetailsViewModel
 * @version V1
 */
class AllianceDetailsViewModel {
    /**
     * Constructs a new <code>AllianceDetailsViewModel</code>.
     * @alias module:model/AllianceDetailsViewModel
     */
    constructor() { 
        
        AllianceDetailsViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AllianceDetailsViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AllianceDetailsViewModel} obj Optional instance to populate.
     * @return {module:model/AllianceDetailsViewModel} The populated <code>AllianceDetailsViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AllianceDetailsViewModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('basic_information')) {
                obj['basic_information'] = ApiClient.convertToType(data['basic_information'], 'String');
            }
            if (data.hasOwnProperty('detail_information')) {
                obj['detail_information'] = ApiClient.convertToType(data['detail_information'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('media')) {
                obj['media'] = ApiClient.convertToType(data['media'], [MediaModelStructure]);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('class')) {
                obj['class'] = ApiClient.convertToType(data['class'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('category_name')) {
                obj['category_name'] = ApiClient.convertToType(data['category_name'], 'String');
            }
            if (data.hasOwnProperty('request_contact_data')) {
                obj['request_contact_data'] = ApiClient.convertToType(data['request_contact_data'], 'Boolean');
            }
            if (data.hasOwnProperty('request_contact_data_fields')) {
                obj['request_contact_data_fields'] = ApiClient.convertToType(data['request_contact_data_fields'], [RequestContactDataFieldsModelStructure]);
            }
            if (data.hasOwnProperty('terms')) {
                obj['terms'] = TermsModel.constructFromObject(data['terms']);
            }
            if (data.hasOwnProperty('user_data')) {
                obj['user_data'] = UserDataViewModel.constructFromObject(data['user_data']);
            }
            if (data.hasOwnProperty('accepted_at')) {
                obj['accepted_at'] = ApiClient.convertToType(data['accepted_at'], 'Date');
            }
            if (data.hasOwnProperty('other_alliances')) {
                obj['other_alliances'] = ApiClient.convertToType(data['other_alliances'], [OtherAlliancesModel]);
            }
            if (data.hasOwnProperty('financial_information')) {
                obj['financial_information'] = ApiClient.convertToType(data['financial_information'], ['String']);
            }
            if (data.hasOwnProperty('acceptance_message')) {
                obj['acceptance_message'] = ApiClient.convertToType(data['acceptance_message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
AllianceDetailsViewModel.prototype['id'] = undefined;

/**
 * @member {Boolean} active
 */
AllianceDetailsViewModel.prototype['active'] = undefined;

/**
 * @member {String} code
 */
AllianceDetailsViewModel.prototype['code'] = undefined;

/**
 * @member {String} name
 */
AllianceDetailsViewModel.prototype['name'] = undefined;

/**
 * @member {String} basic_information
 */
AllianceDetailsViewModel.prototype['basic_information'] = undefined;

/**
 * @member {String} detail_information
 */
AllianceDetailsViewModel.prototype['detail_information'] = undefined;

/**
 * @member {String} logo
 */
AllianceDetailsViewModel.prototype['logo'] = undefined;

/**
 * @member {String} image
 */
AllianceDetailsViewModel.prototype['image'] = undefined;

/**
 * @member {Array.<module:model/MediaModelStructure>} media
 */
AllianceDetailsViewModel.prototype['media'] = undefined;

/**
 * @member {String} url
 */
AllianceDetailsViewModel.prototype['url'] = undefined;

/**
 * @member {String} status
 */
AllianceDetailsViewModel.prototype['status'] = undefined;

/**
 * @member {String} class
 */
AllianceDetailsViewModel.prototype['class'] = undefined;

/**
 * @member {String} type
 */
AllianceDetailsViewModel.prototype['type'] = undefined;

/**
 * @member {String} category
 */
AllianceDetailsViewModel.prototype['category'] = undefined;

/**
 * @member {String} category_name
 */
AllianceDetailsViewModel.prototype['category_name'] = undefined;

/**
 * @member {Boolean} request_contact_data
 */
AllianceDetailsViewModel.prototype['request_contact_data'] = undefined;

/**
 * @member {Array.<module:model/RequestContactDataFieldsModelStructure>} request_contact_data_fields
 */
AllianceDetailsViewModel.prototype['request_contact_data_fields'] = undefined;

/**
 * @member {module:model/TermsModel} terms
 */
AllianceDetailsViewModel.prototype['terms'] = undefined;

/**
 * @member {module:model/UserDataViewModel} user_data
 */
AllianceDetailsViewModel.prototype['user_data'] = undefined;

/**
 * @member {Date} accepted_at
 */
AllianceDetailsViewModel.prototype['accepted_at'] = undefined;

/**
 * @member {Array.<module:model/OtherAlliancesModel>} other_alliances
 */
AllianceDetailsViewModel.prototype['other_alliances'] = undefined;

/**
 * @member {Array.<String>} financial_information
 */
AllianceDetailsViewModel.prototype['financial_information'] = undefined;

/**
 * @member {String} acceptance_message
 */
AllianceDetailsViewModel.prototype['acceptance_message'] = undefined;






export default AllianceDetailsViewModel;

