/**
 * Siigo.Alliances API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AllianceLiteViewModel from './AllianceLiteViewModel';

/**
 * The ApprovedViewModel model module.
 * @module model/ApprovedViewModel
 * @version V1
 */
class ApprovedViewModel {
    /**
     * Constructs a new <code>ApprovedViewModel</code>.
     * @alias module:model/ApprovedViewModel
     */
    constructor() { 
        
        ApprovedViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApprovedViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApprovedViewModel} obj Optional instance to populate.
     * @return {module:model/ApprovedViewModel} The populated <code>ApprovedViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApprovedViewModel();

            if (data.hasOwnProperty('cloud_tenant_id')) {
                obj['cloud_tenant_id'] = ApiClient.convertToType(data['cloud_tenant_id'], 'String');
            }
            if (data.hasOwnProperty('alliances')) {
                obj['alliances'] = ApiClient.convertToType(data['alliances'], [AllianceLiteViewModel]);
            }
            if (data.hasOwnProperty('approved')) {
                obj['approved'] = ApiClient.convertToType(data['approved'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} cloud_tenant_id
 */
ApprovedViewModel.prototype['cloud_tenant_id'] = undefined;

/**
 * @member {Array.<module:model/AllianceLiteViewModel>} alliances
 */
ApprovedViewModel.prototype['alliances'] = undefined;

/**
 * @member {Number} approved
 */
ApprovedViewModel.prototype['approved'] = undefined;






export default ApprovedViewModel;

