/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CityModel model module.
 * @module model/CityModel
 * @version v1
 */
class CityModel {
    /**
     * Constructs a new <code>CityModel</code>.
     * @alias module:model/CityModel
     */
    constructor() { 
        
        CityModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CityModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CityModel} obj Optional instance to populate.
     * @return {module:model/CityModel} The populated <code>CityModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CityModel();

            if (data.hasOwnProperty('country_code')) {
                obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
            }
            if (data.hasOwnProperty('country_name')) {
                obj['country_name'] = ApiClient.convertToType(data['country_name'], 'String');
            }
            if (data.hasOwnProperty('state_code')) {
                obj['state_code'] = ApiClient.convertToType(data['state_code'], 'String');
            }
            if (data.hasOwnProperty('state_name')) {
                obj['state_name'] = ApiClient.convertToType(data['state_name'], 'String');
            }
            if (data.hasOwnProperty('city_code')) {
                obj['city_code'] = ApiClient.convertToType(data['city_code'], 'String');
            }
            if (data.hasOwnProperty('city_name')) {
                obj['city_name'] = ApiClient.convertToType(data['city_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Represents the city Code
 * @member {String} country_code
 */
CityModel.prototype['country_code'] = undefined;

/**
 * Represents the city name
 * @member {String} country_name
 */
CityModel.prototype['country_name'] = undefined;

/**
 * Represents the state code
 * @member {String} state_code
 */
CityModel.prototype['state_code'] = undefined;

/**
 * Represents the state name
 * @member {String} state_name
 */
CityModel.prototype['state_name'] = undefined;

/**
 * Represents the city code
 * @member {String} city_code
 */
CityModel.prototype['city_code'] = undefined;

/**
 * Represents the city name
 * @member {String} city_name
 */
CityModel.prototype['city_name'] = undefined;






export default CityModel;

