/**
 * Siigo.Alliances API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CompanyContactModel from './CompanyContactModel';

/**
 * The CompanyModel model module.
 * @module model/CompanyModel
 * @version V1
 */
class CompanyModel {
    /**
     * Constructs a new <code>CompanyModel</code>.
     * @alias module:model/CompanyModel
     */
    constructor() { 
        
        CompanyModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompanyModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompanyModel} obj Optional instance to populate.
     * @return {module:model/CompanyModel} The populated <code>CompanyModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompanyModel();

            if (data.hasOwnProperty('nit')) {
                obj['nit'] = ApiClient.convertToType(data['nit'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = CompanyContactModel.constructFromObject(data['contact']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} nit
 */
CompanyModel.prototype['nit'] = undefined;

/**
 * @member {String} name
 */
CompanyModel.prototype['name'] = undefined;

/**
 * @member {module:model/CompanyContactModel} contact
 */
CompanyModel.prototype['contact'] = undefined;






export default CompanyModel;

