/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CostCentersViewModel model module.
 * @module model/CostCentersViewModel
 * @version v1
 */
class CostCentersViewModel {
    /**
     * Constructs a new <code>CostCentersViewModel</code>.
     * @alias module:model/CostCentersViewModel
     */
    constructor() { 
        
        CostCentersViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CostCentersViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CostCentersViewModel} obj Optional instance to populate.
     * @return {module:model/CostCentersViewModel} The populated <code>CostCentersViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CostCentersViewModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Represents the id of the cost center, the value of this field must be an integer  number that represents the unique id of the cost center.
 * @member {Number} id
 */
CostCentersViewModel.prototype['id'] = undefined;

/**
 * Represents the identification code of the cost center.   This code will represent the unique code id of the cost center.
 * @member {String} code
 */
CostCentersViewModel.prototype['code'] = undefined;

/**
 * Represents the name of the cost center. This value can be an alphanumeric  name like 'Main Cost Center' or 'Center-1'.
 * @member {String} name
 */
CostCentersViewModel.prototype['name'] = undefined;

/**
 * Represents if the status of a cost center is activated or disabled,   the value of this status will be true (for activated) or false (disabled).  By default, this field will be active.
 * @member {Boolean} active
 */
CostCentersViewModel.prototype['active'] = undefined;






export default CostCentersViewModel;

