/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CurrencyCommand from './CurrencyCommand';
import DocumentCommand from './DocumentCommand';
import JournalEntryItem from './JournalEntryItem';

/**
 * The CreateJournalEntryCommand model module.
 * @module model/CreateJournalEntryCommand
 * @version v1
 */
class CreateJournalEntryCommand {
    /**
     * Constructs a new <code>CreateJournalEntryCommand</code>.
     * @alias module:model/CreateJournalEntryCommand
     */
    constructor() { 
        
        CreateJournalEntryCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateJournalEntryCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateJournalEntryCommand} obj Optional instance to populate.
     * @return {module:model/CreateJournalEntryCommand} The populated <code>CreateJournalEntryCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateJournalEntryCommand();

            if (data.hasOwnProperty('document')) {
                obj['document'] = DocumentCommand.constructFromObject(data['document']);
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = CurrencyCommand.constructFromObject(data['currency']);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [JournalEntryItem]);
            }
            if (data.hasOwnProperty('observations')) {
                obj['observations'] = ApiClient.convertToType(data['observations'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/DocumentCommand} document
 */
CreateJournalEntryCommand.prototype['document'] = undefined;

/**
 * @member {Number} number
 */
CreateJournalEntryCommand.prototype['number'] = undefined;

/**
 * @member {String} date
 */
CreateJournalEntryCommand.prototype['date'] = undefined;

/**
 * @member {module:model/CurrencyCommand} currency
 */
CreateJournalEntryCommand.prototype['currency'] = undefined;

/**
 * @member {Array.<module:model/JournalEntryItem>} items
 */
CreateJournalEntryCommand.prototype['items'] = undefined;

/**
 * @member {String} observations
 */
CreateJournalEntryCommand.prototype['observations'] = undefined;






export default CreateJournalEntryCommand;

