/**
 * Siigo.Alliances API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateUnauthorizedTermsCommand model module.
 * @module model/CreateUnauthorizedTermsCommand
 * @version V1
 */
class CreateUnauthorizedTermsCommand {
    /**
     * Constructs a new <code>CreateUnauthorizedTermsCommand</code>.
     * @alias module:model/CreateUnauthorizedTermsCommand
     */
    constructor() { 
        
        CreateUnauthorizedTermsCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateUnauthorizedTermsCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUnauthorizedTermsCommand} obj Optional instance to populate.
     * @return {module:model/CreateUnauthorizedTermsCommand} The populated <code>CreateUnauthorizedTermsCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUnauthorizedTermsCommand();

            if (data.hasOwnProperty('alliance_code')) {
                obj['alliance_code'] = ApiClient.convertToType(data['alliance_code'], 'String');
            }
            if (data.hasOwnProperty('companies')) {
                obj['companies'] = ApiClient.convertToType(data['companies'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} alliance_code
 */
CreateUnauthorizedTermsCommand.prototype['alliance_code'] = undefined;

/**
 * @member {Array.<String>} companies
 */
CreateUnauthorizedTermsCommand.prototype['companies'] = undefined;






export default CreateUnauthorizedTermsCommand;

