/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CurrencyCommand from './CurrencyCommand';
import Customer from './Customer';
import DocumentCommand from './DocumentCommand';
import Item from './Item';
import Payment from './Payment';

/**
 * The CreateVoucherCommand model module.
 * @module model/CreateVoucherCommand
 * @version 0.1.0
 */
class CreateVoucherCommand {
    /**
     * Constructs a new <code>CreateVoucherCommand</code>.
     * @alias module:model/CreateVoucherCommand
     */
    constructor() { 
        
        CreateVoucherCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateVoucherCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateVoucherCommand} obj Optional instance to populate.
     * @return {module:model/CreateVoucherCommand} The populated <code>CreateVoucherCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateVoucherCommand();

            if (data.hasOwnProperty('document')) {
                obj['document'] = DocumentCommand.constructFromObject(data['document']);
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = Customer.constructFromObject(data['customer']);
            }
            if (data.hasOwnProperty('cost_center')) {
                obj['cost_center'] = ApiClient.convertToType(data['cost_center'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = CurrencyCommand.constructFromObject(data['currency']);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [Item]);
            }
            if (data.hasOwnProperty('payment')) {
                obj['payment'] = Payment.constructFromObject(data['payment']);
            }
            if (data.hasOwnProperty('observations')) {
                obj['observations'] = ApiClient.convertToType(data['observations'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/DocumentCommand} document
 */
CreateVoucherCommand.prototype['document'] = undefined;

/**
 * @member {Number} number
 */
CreateVoucherCommand.prototype['number'] = undefined;

/**
 * @member {String} name
 */
CreateVoucherCommand.prototype['name'] = undefined;

/**
 * @member {String} date
 */
CreateVoucherCommand.prototype['date'] = undefined;

/**
 * @member {String} type
 */
CreateVoucherCommand.prototype['type'] = undefined;

/**
 * @member {module:model/Customer} customer
 */
CreateVoucherCommand.prototype['customer'] = undefined;

/**
 * @member {Number} cost_center
 */
CreateVoucherCommand.prototype['cost_center'] = undefined;

/**
 * @member {module:model/CurrencyCommand} currency
 */
CreateVoucherCommand.prototype['currency'] = undefined;

/**
 * @member {Array.<module:model/Item>} items
 */
CreateVoucherCommand.prototype['items'] = undefined;

/**
 * @member {module:model/Payment} payment
 */
CreateVoucherCommand.prototype['payment'] = undefined;

/**
 * @member {String} observations
 */
CreateVoucherCommand.prototype['observations'] = undefined;






export default CreateVoucherCommand;

