/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomFieldsModel model module.
 * @module model/CustomFieldsModel
 * @version 0.0.0
 */
class CustomFieldsModel {
    /**
     * Constructs a new <code>CustomFieldsModel</code>.
     * @alias module:model/CustomFieldsModel
     */
    constructor() { 
        
        CustomFieldsModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomFieldsModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomFieldsModel} obj Optional instance to populate.
     * @return {module:model/CustomFieldsModel} The populated <code>CustomFieldsModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFieldsModel();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Represents the Id of additional field  For example, an additional field called 'YearsOld'.
 * @member {String} key
 */
CustomFieldsModel.prototype['key'] = undefined;

/**
 * Represents the value of additional field.  For example, this field can be '29'.
 * @member {String} value
 */
CustomFieldsModel.prototype['value'] = undefined;






export default CustomFieldsModel;

