/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomerDeleteViewModel model module.
 * @module model/CustomerDeleteViewModel
 * @version v1
 */
class CustomerDeleteViewModel {
    /**
     * Constructs a new <code>CustomerDeleteViewModel</code>.
     * @alias module:model/CustomerDeleteViewModel
     */
    constructor() { 
        
        CustomerDeleteViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomerDeleteViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerDeleteViewModel} obj Optional instance to populate.
     * @return {module:model/CustomerDeleteViewModel} The populated <code>CustomerDeleteViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerDeleteViewModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('deleted')) {
                obj['deleted'] = ApiClient.convertToType(data['deleted'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Represents the unique Id of customer, this value must be a Guid  with the next format 00000000-0000-0000-0000-000000000000.
 * @member {String} id
 */
CustomerDeleteViewModel.prototype['id'] = undefined;

/**
 * Represent the deleted status of customer.
 * @member {Boolean} deleted
 */
CustomerDeleteViewModel.prototype['deleted'] = undefined;






export default CustomerDeleteViewModel;

