/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DocumentCommand model module.
 * @module model/DocumentCommand
 * @version v1
 */
class DocumentCommand {
    /**
     * Constructs a new <code>DocumentCommand</code>.
     * @alias module:model/DocumentCommand
     */
    constructor() { 
        
        DocumentCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DocumentCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocumentCommand} obj Optional instance to populate.
     * @return {module:model/DocumentCommand} The populated <code>DocumentCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentCommand();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Represents the Id of document. The value of this field must be an integer  number that represents the unique id of the document type, for example '22'.
 * @member {Number} id
 */
DocumentCommand.prototype['id'] = undefined;






export default DocumentCommand;

