/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EInvoiceErrorViewModel from './EInvoiceErrorViewModel';

/**
 * The EInvoiceErrorsViewModel model module.
 * @module model/EInvoiceErrorsViewModel
 * @version v1
 */
class EInvoiceErrorsViewModel {
    /**
     * Constructs a new <code>EInvoiceErrorsViewModel</code>.
     * @alias module:model/EInvoiceErrorsViewModel
     */
    constructor() { 
        
        EInvoiceErrorsViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EInvoiceErrorsViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EInvoiceErrorsViewModel} obj Optional instance to populate.
     * @return {module:model/EInvoiceErrorsViewModel} The populated <code>EInvoiceErrorsViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EInvoiceErrorsViewModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [EInvoiceErrorViewModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
EInvoiceErrorsViewModel.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/EInvoiceErrorViewModel>} errors
 */
EInvoiceErrorsViewModel.prototype['errors'] = undefined;






export default EInvoiceErrorsViewModel;

