/**
 * Siigo.Alliances API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CompanyModel from './CompanyModel';
import FinancialInformationModel from './FinancialInformationModel';

/**
 * The FinancialInformationViewModel model module.
 * @module model/FinancialInformationViewModel
 * @version V1
 */
class FinancialInformationViewModel {
    /**
     * Constructs a new <code>FinancialInformationViewModel</code>.
     * @alias module:model/FinancialInformationViewModel
     */
    constructor() { 
        
        FinancialInformationViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FinancialInformationViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FinancialInformationViewModel} obj Optional instance to populate.
     * @return {module:model/FinancialInformationViewModel} The populated <code>FinancialInformationViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FinancialInformationViewModel();

            if (data.hasOwnProperty('company')) {
                obj['company'] = CompanyModel.constructFromObject(data['company']);
            }
            if (data.hasOwnProperty('acceptance_date')) {
                obj['acceptance_date'] = ApiClient.convertToType(data['acceptance_date'], 'Date');
            }
            if (data.hasOwnProperty('financial_information')) {
                obj['financial_information'] = ApiClient.convertToType(data['financial_information'], [FinancialInformationModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CompanyModel} company
 */
FinancialInformationViewModel.prototype['company'] = undefined;

/**
 * @member {Date} acceptance_date
 */
FinancialInformationViewModel.prototype['acceptance_date'] = undefined;

/**
 * @member {Array.<module:model/FinancialInformationModel>} financial_information
 */
FinancialInformationViewModel.prototype['financial_information'] = undefined;






export default FinancialInformationViewModel;

