/**
 * Siigo.Alliances API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TermsInfoViewModel from './TermsInfoViewModel';
import UserDataViewModel from './UserDataViewModel';

/**
 * The HistoryDetailViewModel model module.
 * @module model/HistoryDetailViewModel
 * @version V1
 */
class HistoryDetailViewModel {
    /**
     * Constructs a new <code>HistoryDetailViewModel</code>.
     * @alias module:model/HistoryDetailViewModel
     */
    constructor() { 
        
        HistoryDetailViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HistoryDetailViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HistoryDetailViewModel} obj Optional instance to populate.
     * @return {module:model/HistoryDetailViewModel} The populated <code>HistoryDetailViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HistoryDetailViewModel();

            if (data.hasOwnProperty('history_id')) {
                obj['history_id'] = ApiClient.convertToType(data['history_id'], 'String');
            }
            if (data.hasOwnProperty('company_id')) {
                obj['company_id'] = ApiClient.convertToType(data['company_id'], 'String');
            }
            if (data.hasOwnProperty('alliance_id')) {
                obj['alliance_id'] = ApiClient.convertToType(data['alliance_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Boolean');
            }
            if (data.hasOwnProperty('terms')) {
                obj['terms'] = TermsInfoViewModel.constructFromObject(data['terms']);
            }
            if (data.hasOwnProperty('user_data')) {
                obj['user_data'] = UserDataViewModel.constructFromObject(data['user_data']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} history_id
 */
HistoryDetailViewModel.prototype['history_id'] = undefined;

/**
 * @member {String} company_id
 */
HistoryDetailViewModel.prototype['company_id'] = undefined;

/**
 * @member {String} alliance_id
 */
HistoryDetailViewModel.prototype['alliance_id'] = undefined;

/**
 * @member {Boolean} status
 */
HistoryDetailViewModel.prototype['status'] = undefined;

/**
 * @member {module:model/TermsInfoViewModel} terms
 */
HistoryDetailViewModel.prototype['terms'] = undefined;

/**
 * @member {module:model/UserDataViewModel} user_data
 */
HistoryDetailViewModel.prototype['user_data'] = undefined;

/**
 * @member {Date} created_at
 */
HistoryDetailViewModel.prototype['created_at'] = undefined;






export default HistoryDetailViewModel;

