/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InvoiceCustomerModel model module.
 * @module model/InvoiceCustomerModel
 * @version v1
 */
class InvoiceCustomerModel {
    /**
     * Constructs a new <code>InvoiceCustomerModel</code>.
     * @alias module:model/InvoiceCustomerModel
     */
    constructor() { 
        
        InvoiceCustomerModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InvoiceCustomerModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvoiceCustomerModel} obj Optional instance to populate.
     * @return {module:model/InvoiceCustomerModel} The populated <code>InvoiceCustomerModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvoiceCustomerModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('identification')) {
                obj['identification'] = ApiClient.convertToType(data['identification'], 'String');
            }
            if (data.hasOwnProperty('branch_office')) {
                obj['branch_office'] = ApiClient.convertToType(data['branch_office'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Represents the unique Id of customer, this value must be a \"Guid\"  with the next format 00000000-0000-0000-0000-000000000000
 * @member {String} id
 */
InvoiceCustomerModel.prototype['id'] = undefined;

/**
 * Represents the identification number of customer
 * @member {String} identification
 */
InvoiceCustomerModel.prototype['identification'] = undefined;

/**
 * Represents the branch office number of the customer, default value will be 0
 * @member {Number} branch_office
 */
InvoiceCustomerModel.prototype['branch_office'] = undefined;






export default InvoiceCustomerModel;

