/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ItemDueCommand model module.
 * @module model/ItemDueCommand
 * @version v1
 */
class ItemDueCommand {
    /**
     * Constructs a new <code>ItemDueCommand</code>.
     * @alias module:model/ItemDueCommand
     */
    constructor() { 
        
        ItemDueCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ItemDueCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ItemDueCommand} obj Optional instance to populate.
     * @return {module:model/ItemDueCommand} The populated <code>ItemDueCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ItemDueCommand();

            if (data.hasOwnProperty('prefix')) {
                obj['prefix'] = ApiClient.convertToType(data['prefix'], 'String');
            }
            if (data.hasOwnProperty('consecutive')) {
                obj['consecutive'] = ApiClient.convertToType(data['consecutive'], 'Number');
            }
            if (data.hasOwnProperty('quote')) {
                obj['quote'] = ApiClient.convertToType(data['quote'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Represents the prefix of the invoice to which the credit or payment will be applied.
 * @member {String} prefix
 */
ItemDueCommand.prototype['prefix'] = undefined;

/**
 * Represents the consecutive of the invoice to which the credit or payment will be applied.
 * @member {Number} consecutive
 */
ItemDueCommand.prototype['consecutive'] = undefined;

/**
 * Represents the quota number of the credit or payment.
 * @member {Number} quote
 */
ItemDueCommand.prototype['quote'] = undefined;

/**
 * Represents the payment date of the fee.  This field must be the next format 'yyyy-MM-dd'.
 * @member {String} date
 */
ItemDueCommand.prototype['date'] = undefined;






export default ItemDueCommand;

