/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Account from './Account';
import FixedAssetCommand from './FixedAssetCommand';
import ItemDueCommand from './ItemDueCommand';
import JournalEntryProductCommand from './JournalEntryProductCommand';
import LiteCustomerCommand from './LiteCustomerCommand';
import TaxesCommand from './TaxesCommand';

/**
 * The JournalEntryItem model module.
 * @module model/JournalEntryItem
 * @version 0.1.0
 */
class JournalEntryItem {
    /**
     * Constructs a new <code>JournalEntryItem</code>.
     * @alias module:model/JournalEntryItem
     */
    constructor() { 
        
        JournalEntryItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JournalEntryItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JournalEntryItem} obj Optional instance to populate.
     * @return {module:model/JournalEntryItem} The populated <code>JournalEntryItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JournalEntryItem();

            if (data.hasOwnProperty('account')) {
                obj['account'] = Account.constructFromObject(data['account']);
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = LiteCustomerCommand.constructFromObject(data['customer']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('tax')) {
                obj['tax'] = TaxesCommand.constructFromObject(data['tax']);
            }
            if (data.hasOwnProperty('due')) {
                obj['due'] = ItemDueCommand.constructFromObject(data['due']);
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = JournalEntryProductCommand.constructFromObject(data['product']);
            }
            if (data.hasOwnProperty('cost_center')) {
                obj['cost_center'] = ApiClient.convertToType(data['cost_center'], 'Number');
            }
            if (data.hasOwnProperty('fixed_asset')) {
                obj['fixed_asset'] = FixedAssetCommand.constructFromObject(data['fixed_asset']);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Account} account
 */
JournalEntryItem.prototype['account'] = undefined;

/**
 * @member {module:model/LiteCustomerCommand} customer
 */
JournalEntryItem.prototype['customer'] = undefined;

/**
 * @member {String} description
 */
JournalEntryItem.prototype['description'] = undefined;

/**
 * @member {module:model/TaxesCommand} tax
 */
JournalEntryItem.prototype['tax'] = undefined;

/**
 * @member {module:model/ItemDueCommand} due
 */
JournalEntryItem.prototype['due'] = undefined;

/**
 * @member {module:model/JournalEntryProductCommand} product
 */
JournalEntryItem.prototype['product'] = undefined;

/**
 * @member {Number} cost_center
 */
JournalEntryItem.prototype['cost_center'] = undefined;

/**
 * @member {module:model/FixedAssetCommand} fixed_asset
 */
JournalEntryItem.prototype['fixed_asset'] = undefined;

/**
 * @member {Number} value
 */
JournalEntryItem.prototype['value'] = undefined;






export default JournalEntryItem;

