/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JournalEntryViewModel from './JournalEntryViewModel';
import LinksPagination from './LinksPagination';
import PageListModel from './PageListModel';

/**
 * The JournalsEntryViewModel model module.
 * @module model/JournalsEntryViewModel
 * @version v1
 */
class JournalsEntryViewModel {
    /**
     * Constructs a new <code>JournalsEntryViewModel</code>.
     * Class that contain the jsons that the client will see after request  a journal entry list with pagination that came from msacentryqueries
     * @alias module:model/JournalsEntryViewModel
     */
    constructor() { 
        
        JournalsEntryViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JournalsEntryViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JournalsEntryViewModel} obj Optional instance to populate.
     * @return {module:model/JournalsEntryViewModel} The populated <code>JournalsEntryViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JournalsEntryViewModel();

            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = PageListModel.constructFromObject(data['pagination']);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [JournalEntryViewModel]);
            }
            if (data.hasOwnProperty('__links')) {
                obj['__links'] = LinksPagination.constructFromObject(data['__links']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PageListModel} pagination
 */
JournalsEntryViewModel.prototype['pagination'] = undefined;

/**
 * @member {Array.<module:model/JournalEntryViewModel>} results
 */
JournalsEntryViewModel.prototype['results'] = undefined;

/**
 * @member {module:model/LinksPagination} __links
 */
JournalsEntryViewModel.prototype['__links'] = undefined;






export default JournalsEntryViewModel;

