/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JournalEntryWarehouseModel model module.
 * @module model/JournalEntryWarehouseModel
 * @version 0.0.0
 */
class JournalEntryWarehouseModel {
    /**
     * Constructs a new <code>JournalEntryWarehouseModel</code>.
     * @alias module:model/JournalEntryWarehouseModel
     */
    constructor() { 
        
        JournalEntryWarehouseModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JournalEntryWarehouseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JournalEntryWarehouseModel} obj Optional instance to populate.
     * @return {module:model/JournalEntryWarehouseModel} The populated <code>JournalEntryWarehouseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JournalEntryWarehouseModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Represents the id of warehouse, by default this field will be null.
 * @member {Number} id
 */
JournalEntryWarehouseModel.prototype['id'] = undefined;

/**
 * Represents the name of warehouse.
 * @member {String} name
 */
JournalEntryWarehouseModel.prototype['name'] = undefined;






export default JournalEntryWarehouseModel;

