/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MailCommand model module.
 * @module model/MailCommand
 * @version v1
 */
class MailCommand {
    /**
     * Constructs a new <code>MailCommand</code>.
     * @alias module:model/MailCommand
     */
    constructor() { 
        
        MailCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MailCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MailCommand} obj Optional instance to populate.
     * @return {module:model/MailCommand} The populated <code>MailCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MailCommand();

            if (data.hasOwnProperty('send')) {
                obj['send'] = ApiClient.convertToType(data['send'], 'Boolean');
            }
            if (data.hasOwnProperty('copy_to')) {
                obj['copy_to'] = ApiClient.convertToType(data['copy_to'], 'String');
            }
        }
        return obj;
    }


}

/**
 * It must be set to true to send the document by email, otherwise it will not be sent.
 * @member {Boolean} send
 */
MailCommand.prototype['send'] = undefined;

/**
 * A maximum of five additional email addresses can be configured to send the document by email.
 * @member {String} copy_to
 */
MailCommand.prototype['copy_to'] = undefined;






export default MailCommand;

