/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetadataModel model module.
 * @module model/MetadataModel
 * @version v1
 */
class MetadataModel {
    /**
     * Constructs a new <code>MetadataModel</code>.
     * @alias module:model/MetadataModel
     */
    constructor() { 
        
        MetadataModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetadataModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetadataModel} obj Optional instance to populate.
     * @return {module:model/MetadataModel} The populated <code>MetadataModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetadataModel();

            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('last_updated')) {
                obj['last_updated'] = ApiClient.convertToType(data['last_updated'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * Represents the creation date of organization.
 * @member {Date} created
 */
MetadataModel.prototype['created'] = undefined;

/**
 * Represents the last update date of organization, this field by the default will be null.
 * @member {Date} last_updated
 */
MetadataModel.prototype['last_updated'] = undefined;






export default MetadataModel;

