/**
 * Siigo.Alliances API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OtherAlliancesModel model module.
 * @module model/OtherAlliancesModel
 * @version V1
 */
class OtherAlliancesModel {
    /**
     * Constructs a new <code>OtherAlliancesModel</code>.
     * @alias module:model/OtherAlliancesModel
     */
    constructor() { 
        
        OtherAlliancesModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OtherAlliancesModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OtherAlliancesModel} obj Optional instance to populate.
     * @return {module:model/OtherAlliancesModel} The populated <code>OtherAlliancesModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OtherAlliancesModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('category_name')) {
                obj['category_name'] = ApiClient.convertToType(data['category_name'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
OtherAlliancesModel.prototype['id'] = undefined;

/**
 * @member {String} name
 */
OtherAlliancesModel.prototype['name'] = undefined;

/**
 * @member {String} category
 */
OtherAlliancesModel.prototype['category'] = undefined;

/**
 * @member {String} category_name
 */
OtherAlliancesModel.prototype['category_name'] = undefined;

/**
 * @member {String} logo
 */
OtherAlliancesModel.prototype['logo'] = undefined;






export default OtherAlliancesModel;

