/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentsCommand model module.
 * @module model/PaymentsCommand
 * @version v1
 */
class PaymentsCommand {
    /**
     * Constructs a new <code>PaymentsCommand</code>.
     * @alias module:model/PaymentsCommand
     */
    constructor() { 
        
        PaymentsCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentsCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentsCommand} obj Optional instance to populate.
     * @return {module:model/PaymentsCommand} The populated <code>PaymentsCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentsCommand();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('due_date')) {
                obj['due_date'] = ApiClient.convertToType(data['due_date'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Represents the id of payment method
 * @member {Number} id
 */
PaymentsCommand.prototype['id'] = undefined;

/**
 * represents the amount to paid per installment,  this value will be associated to payment method
 * @member {Number} value
 */
PaymentsCommand.prototype['value'] = undefined;

/**
 * Represents the date of fee payment
 * @member {String} due_date
 */
PaymentsCommand.prototype['due_date'] = undefined;






export default PaymentsCommand;

