/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PriceListsViewModel model module.
 * @module model/PriceListsViewModel
 * @version 0.1.0
 */
class PriceListsViewModel {
    /**
     * Constructs a new <code>PriceListsViewModel</code>.
     * Viewmodel Specifically made for the clients, based on the data returned by the queries.
     * @alias module:model/PriceListsViewModel
     */
    constructor() { 
        
        PriceListsViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PriceListsViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PriceListsViewModel} obj Optional instance to populate.
     * @return {module:model/PriceListsViewModel} The populated <code>PriceListsViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PriceListsViewModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Unique identifier of the price list.
 * @member {Number} id
 */
PriceListsViewModel.prototype['id'] = undefined;

/**
 * Name of the price list.
 * @member {String} name
 */
PriceListsViewModel.prototype['name'] = undefined;

/**
 * Indicates if the price list in use.
 * @member {Boolean} active
 */
PriceListsViewModel.prototype['active'] = undefined;

/**
 * Price list position.
 * @member {Number} position
 */
PriceListsViewModel.prototype['position'] = undefined;






export default PriceListsViewModel;

