/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PriceListItemViewModel from './PriceListItemViewModel';

/**
 * The PriceListViewModel model module.
 * @module model/PriceListViewModel
 * @version 0.0.0
 */
class PriceListViewModel {
    /**
     * Constructs a new <code>PriceListViewModel</code>.
     * @alias module:model/PriceListViewModel
     */
    constructor() { 
        
        PriceListViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PriceListViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PriceListViewModel} obj Optional instance to populate.
     * @return {module:model/PriceListViewModel} The populated <code>PriceListViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PriceListViewModel();

            if (data.hasOwnProperty('currency_code')) {
                obj['currency_code'] = ApiClient.convertToType(data['currency_code'], 'String');
            }
            if (data.hasOwnProperty('price_list')) {
                obj['price_list'] = ApiClient.convertToType(data['price_list'], [PriceListItemViewModel]);
            }
        }
        return obj;
    }


}

/**
 * Represents the currency code.
 * @member {String} currency_code
 */
PriceListViewModel.prototype['currency_code'] = undefined;

/**
 * Contains a price list.
 * @member {Array.<module:model/PriceListItemViewModel>} price_list
 */
PriceListViewModel.prototype['price_list'] = undefined;






export default PriceListViewModel;

