/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TaxViewModel model module.
 * @module model/TaxViewModel
 * @version v1
 */
class TaxViewModel {
    /**
     * Constructs a new <code>TaxViewModel</code>.
     * @alias module:model/TaxViewModel
     */
    constructor() { 
        
        TaxViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TaxViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TaxViewModel} obj Optional instance to populate.
     * @return {module:model/TaxViewModel} The populated <code>TaxViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaxViewModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('percentage')) {
                obj['percentage'] = ApiClient.convertToType(data['percentage'], 'Number');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
TaxViewModel.prototype['id'] = undefined;

/**
 * @member {String} name
 */
TaxViewModel.prototype['name'] = undefined;

/**
 * @member {String} type
 */
TaxViewModel.prototype['type'] = undefined;

/**
 * @member {Number} percentage
 */
TaxViewModel.prototype['percentage'] = undefined;

/**
 * @member {Boolean} active
 */
TaxViewModel.prototype['active'] = undefined;






export default TaxViewModel;

