/**
 * Siigo.Alliances API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserDataViewModel model module.
 * @module model/UserDataViewModel
 * @version V1
 */
class UserDataViewModel {
    /**
     * Constructs a new <code>UserDataViewModel</code>.
     * @alias module:model/UserDataViewModel
     */
    constructor() { 
        
        UserDataViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserDataViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserDataViewModel} obj Optional instance to populate.
     * @return {module:model/UserDataViewModel} The populated <code>UserDataViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDataViewModel();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('user_name')) {
                obj['user_name'] = ApiClient.convertToType(data['user_name'], 'String');
            }
            if (data.hasOwnProperty('full_name')) {
                obj['full_name'] = ApiClient.convertToType(data['full_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('mobile')) {
                obj['mobile'] = ApiClient.convertToType(data['mobile'], 'String');
            }
            if (data.hasOwnProperty('additional_data')) {
                obj['additional_data'] = ApiClient.convertToType(data['additional_data'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * @member {String} user_id
 */
UserDataViewModel.prototype['user_id'] = undefined;

/**
 * @member {String} user_name
 */
UserDataViewModel.prototype['user_name'] = undefined;

/**
 * @member {String} full_name
 */
UserDataViewModel.prototype['full_name'] = undefined;

/**
 * @member {String} email
 */
UserDataViewModel.prototype['email'] = undefined;

/**
 * @member {String} mobile
 */
UserDataViewModel.prototype['mobile'] = undefined;

/**
 * @member {Object.<String, String>} additional_data
 */
UserDataViewModel.prototype['additional_data'] = undefined;






export default UserDataViewModel;

