/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CurrencyModel from './CurrencyModel';
import CustomerVoucher from './CustomerVoucher';
import DocumentVoucher from './DocumentVoucher';
import ItemVoucher from './ItemVoucher';
import Metadata from './Metadata';
import PaymentsModel from './PaymentsModel';

/**
 * The VoucherViewModel model module.
 * @module model/VoucherViewModel
 * @version 0.1.0
 */
class VoucherViewModel {
    /**
     * Constructs a new <code>VoucherViewModel</code>.
     * @alias module:model/VoucherViewModel
     */
    constructor() { 
        
        VoucherViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VoucherViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VoucherViewModel} obj Optional instance to populate.
     * @return {module:model/VoucherViewModel} The populated <code>VoucherViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VoucherViewModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('document')) {
                obj['document'] = DocumentVoucher.constructFromObject(data['document']);
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('cost_center')) {
                obj['cost_center'] = ApiClient.convertToType(data['cost_center'], 'Number');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = CustomerVoucher.constructFromObject(data['customer']);
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = CurrencyModel.constructFromObject(data['currency']);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [ItemVoucher]);
            }
            if (data.hasOwnProperty('payment')) {
                obj['payment'] = PaymentsModel.constructFromObject(data['payment']);
            }
            if (data.hasOwnProperty('observations')) {
                obj['observations'] = ApiClient.convertToType(data['observations'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
VoucherViewModel.prototype['id'] = undefined;

/**
 * @member {module:model/DocumentVoucher} document
 */
VoucherViewModel.prototype['document'] = undefined;

/**
 * @member {Number} number
 */
VoucherViewModel.prototype['number'] = undefined;

/**
 * @member {String} name
 */
VoucherViewModel.prototype['name'] = undefined;

/**
 * @member {String} date
 */
VoucherViewModel.prototype['date'] = undefined;

/**
 * @member {String} type
 */
VoucherViewModel.prototype['type'] = undefined;

/**
 * @member {Number} cost_center
 */
VoucherViewModel.prototype['cost_center'] = undefined;

/**
 * @member {module:model/CustomerVoucher} customer
 */
VoucherViewModel.prototype['customer'] = undefined;

/**
 * @member {module:model/CurrencyModel} currency
 */
VoucherViewModel.prototype['currency'] = undefined;

/**
 * @member {Array.<module:model/ItemVoucher>} items
 */
VoucherViewModel.prototype['items'] = undefined;

/**
 * @member {module:model/PaymentsModel} payment
 */
VoucherViewModel.prototype['payment'] = undefined;

/**
 * @member {String} observations
 */
VoucherViewModel.prototype['observations'] = undefined;

/**
 * @member {module:model/Metadata} metadata
 */
VoucherViewModel.prototype['metadata'] = undefined;






export default VoucherViewModel;

