/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LinksPagination from './LinksPagination';
import PageListModel from './PageListModel';
import VoucherViewModel from './VoucherViewModel';

/**
 * The VouchersViewModel model module.
 * @module model/VouchersViewModel
 * @version v1
 */
class VouchersViewModel {
    /**
     * Constructs a new <code>VouchersViewModel</code>.
     * @alias module:model/VouchersViewModel
     */
    constructor() { 
        
        VouchersViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VouchersViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VouchersViewModel} obj Optional instance to populate.
     * @return {module:model/VouchersViewModel} The populated <code>VouchersViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VouchersViewModel();

            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = PageListModel.constructFromObject(data['pagination']);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [VoucherViewModel]);
            }
            if (data.hasOwnProperty('__links')) {
                obj['__links'] = LinksPagination.constructFromObject(data['__links']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PageListModel} pagination
 */
VouchersViewModel.prototype['pagination'] = undefined;

/**
 * @member {Array.<module:model/VoucherViewModel>} results
 */
VouchersViewModel.prototype['results'] = undefined;

/**
 * @member {module:model/LinksPagination} __links
 */
VouchersViewModel.prototype['__links'] = undefined;






export default VouchersViewModel;

