/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PaymentTypesViewModel from '../model/PaymentTypesViewModel';

/**
* PaymentTypes service.
* @module api/PaymentTypesApi
* @version v1
*/
export default class PaymentTypesApi {

    /**
    * Constructs a new PaymentTypesApi. 
    * @alias module:api/PaymentTypesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get a list of Payment Types.
     * @param {Object} opts Optional parameters
     * @param {String} opts.documentType Represents the document type of payment method
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaymentTypesViewModel} and HTTP response
     */
    v1PaymentTypesGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'document_type': opts['documentType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = PaymentTypesViewModel;
      return this.apiClient.callApi(
        '/v1/payment-types', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a list of Payment Types.
     * @param {Object} opts Optional parameters
     * @param {String} opts.documentType Represents the document type of payment method
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaymentTypesViewModel}
     */
    v1PaymentTypesGet(opts) {
      return this.v1PaymentTypesGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
