/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SiigoApi);
  }
}(this, function(expect, SiigoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SiigoApi.JournalEntryProductModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JournalEntryProductModel', function() {
    it('should create an instance of JournalEntryProductModel', function() {
      // uncomment below and update the code to test JournalEntryProductModel
      var instance = new SiigoApi.JournalEntryProductModel();
      expect(instance).to.be.a(SiigoApi.JournalEntryProductModel);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      var instance = new SiigoApi.JournalEntryProductModel();
      expect(instance.id).to.be(undefined);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      var instance = new SiigoApi.JournalEntryProductModel();
      expect(instance.code).to.be(undefined);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      var instance = new SiigoApi.JournalEntryProductModel();
      expect(instance.name).to.be(undefined);
    });

    it('should have the property warehouse (base name: "warehouse")', function() {
      // uncomment below and update the code to test the property warehouse
      var instance = new SiigoApi.JournalEntryProductModel();
      expect(instance.warehouse).to.be(undefined);
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      var instance = new SiigoApi.JournalEntryProductModel();
      expect(instance.quantity).to.be(undefined);
    });

  });

}));
